### ISSUE TITLE
Feature request: Schematic/example for Maker Kit

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot-archived/docs-old#131]
@joegoggins,

there's one thread bubbling up with 'Photoresistor how-to' where new makers/spark owners are asking how they can hook up the stuff and run some test code to see how it works.

https://community.spark.io/t/photoresistor-how-to/3615/1

I'm sure they can all search online and find the answers or be guided by the community on what to do.

Would having this in the docs be nice? :)

I wouldn't mind helping out but you guys are gonna do so much better with the high res photos etc.

Backlog maybe?

**Comment by joegoggins** [comment]
That's a a cool idea @kennethlimcp . It'd be sweet to have a nice example for a component that comes in the maker kit!

Do you have a maker kit? Or do you have the required components to wire this up and write firmware for it? It'd be awesome to have help putting this together.

**Comment by kennethlimcp** [comment]
Sadly I don't have the maker kit but some components commonly used by hobbyists :)

Let me see what I can do for a start!

**Comment by kennethlimcp** [comment]
@joegoggins take a look at this:

https://github.com/kennethlimcp/docs/blob/master/docs/beginners.md

I made up something to kickstart this and get the ball rolling. 

Content for each activity is roughly as such:
- Description
- Parts needed
- Schematic + breadboard visual
- Using Tinker app to try
- Example code
- Tinker-ables (stuff they can modify for more hands on)

We can discuss on the format, what to be inside etc..

Did a little planning on how the flow of learning should be for the Maker kit owners:

1) LED + Resistor --> Blink on/off (digitalwrite)
2) Button --> On and off the LED using user input (digitalread)
3) Photoresistor --> On/off LED depending on light condition (analogread)
4) Potentiometer --> Vary the blinking time of the LED (analogread)
5) Piezo + Transistor --> Make different tone by turning Pot (analogwrite)
6) RGB LED --> mix the colors of led depending on the analog voltage on the Bi-led (analogwrite)
7) Servo --> Control servo position using Pot or step per button pressed (analogwrite + analogread)

The final one we can give them a design challenge to maybe do a sequence of events with all the knowledge gained from the above activities.

Let me know what you think :)

**Comment by joegoggins** [comment]
Yea Kenneth! This is awesome, thanks so much for getting the ball rolling.

Let's package that "beginners.md" content with the [app examples repo](https://github.com/spark/examples). We're hoping this repo will become the official source of truth for awesome-sauce examples--we going to find a way to merge code examples from this repo into the docs site programmatically.  I think this particular content should live in the led_blink example.  Please merge your content with the existing readme there and issue a pull request. Yay!

Regarding the other stuff. Yes. Yes. Yes. I love the idea of having learning activities associated with all of the stuff in a maker kit....But, first let's do one at a time starting with the LED blink example. Once that is looking good, let's look at the current state of the examples repo and figure out what should come next, some of which will definitely be the ideas you are proposing.

**Comment by kennethlimcp** [comment]
So basically the LED example I have done up is already complete and usable.

Just need to figure out where to merge it and make things proper
(formatting, header etc)

So at this point, there's no need for me to do up examples based on other
stuff in the kit?

Sent from S4
Kenneth Lim

**Comment by joegoggins** [comment]
Agreed. Your LED Example is great, just need to bring it into the example
repo. I like your "activities" section too in the README. I'm thinking
maybe the general format of the readme might be like this:
1. about
2. required materials
3. circuit diagram/hardware setup
4. how to use
5. activities

"So at this point, there's no need for me to do up examples based on
other stuff
in the kit?

> > > Right right, I was thinking that since you didn't have a Maker Kit,
> > > that would be difficult, however I'm now seeing above that you do have many
> > > of the required components. If the components are the same, then yes, that
> > > would be great! Let's start with one of the above that you proposed (you
> > > pick) in the examples repo, refine it, then once it's looking good jump on
> > > to another one. The reason I don't want to do them all at once is that this
> > > "accept firmware examples via pull requests to repo" thing is a new process
> > > and I know there are going to be changes needed to make it awesome--I'd
> > > like to take it slow initially and process suggestions for improvements
> > > very quickly before scaling it up. Let me know if that doesn't make sense.

**Comment by kennethlimcp** [comment]
Ah I totally missed out the examples section in the docs.

Seems like the example up there is similar to what I wrote :)

I'm going to make things as simple as possible in each activity and they
can probably be available to the users as long as there's no bug in code or
incorrectly wired stuff.

Going to focus on really minimal code and wiring to get their feet wet in the readme!

They are gonna find the information somewhere online so why not make docs
the places to get it? That way, we get more feedback to make it
awesomely-awesome but won't differ much since everything requires a
schematic and code :D

I guess it's definitely better than having coming soon section that has
been there for months!

Sent from S4
Kenneth Lim
