### ISSUE TITLE
Add in rating for DPDT

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot-archived/docs-old#144]
We either add them in proper or remove the half-description?

Doesn't look professional that way!

https://github.com/spark/docs/blob/master/docs/shields.md#15-dpdt-switch-2

**Comment by technobly** [comment]
@brandoaire do you have a part number for this DPDT switch so we can look up the contact ratings?

Looks like we need something similar for the Rotary Potentiometer, and Red/Green LEDs.
