### ISSUE TITLE
Dark Text in HTML Tables on right side

### ISSUE THREAD

**Issue by bkobkobko** [particle-iot-archived/docs-old#158]
In some areas there are HTML tables on the "example" side (on the right) that render very dark.  In Chrome and Safari they are light grey on dark grey and none too readable.

Examples are found in 

Spark Core Datasheet sections 
- Memory Mapping
- Electrical Characteristics
- Physical Layout

Shields and Kits
- Pin Mapping

There could be others but those are the ones I saw.

I am not sure where to fix this in the CSS, but I know @technobly  has been in there fixing other things!

**Comment by technobly** [comment]
I'll take a look at it today ;-)

**Comment by technobly** [comment]
Fixed! https://github.com/spark/docs/commit/5e28d925df182952697e367d7c62f447116b623e
