### ISSUE TITLE
change background colour for right column

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot-archived/docs-old#198]
The black against grey text is barely readable for http://docs.spark.io/hardware/

![screen shot 2014-07-22 at 16 28 51](https://cloud.githubusercontent.com/assets/6760914/3655493/67c56f92-117a-11e4-94d2-3fbd48106008.png)

**Comment by technobly** [comment]
Try a code block like the Shied Shield pinout.

**Comment by kennethlimcp** [comment]
@technobly, i just tried and they are using tables which doesn't get recognized the moment you add the code block formatting.

I don't want to do it manually like the shield shield pin-out as well....

It would be much better for the background colour to be lighten or make the text white....

**Comment by technobly** [comment]
Ok then we just need to alter the CSS for default markdown text to a much lighter color.

**Comment by zsup** [comment]
Fixed with ac03781, deploying now

**Comment by kennethlimcp** [comment]
Thanks @zs- ! soooo much better now ;)
