### ISSUE TITLE
Overview/Getting Started Page

### ISSUE THREAD

**Issue by towynlin** [particle-iot-archived/docs-old#2]
We want to walk people through the basics to make it as easy as possible to get started.  We need to keep the assumptions of prior knowledge to a minimum.  Model after:
- https://www.balancedpayments.com/docs/overview?language=bash
- https://stripe.com/docs/tutorials/checkout

Would be nice to have this for the local hackathon, but it's required by the Kickstarter launch.

**Comment by wgbartley** [comment]
Looks like the Getting Started section is as good as, if not better than, your cited examples.  Should this issue be closed?

**Comment by joegoggins** [comment]
YES! Cheers to closing stuff that's done!
