### ISSUE TITLE
Firmware reference crashes iOS devices

### ISSUE THREAD

**Issue by eddiezane** [particle-iot-archived/docs-old#200]
Visiting http://docs.spark.io/firmware/ causes a LowMemory crash on both my iPhone 5s and iPad mini. This happens with both Chrome and Safari. Below is the log.

```
{"version":"104","bug_type":"198","os_version":"iPhone OS 7.1.2 (11D257)"}
Incident Identifier: 0562CEDB-C0BD-4DA9-83FB-4D2EA9B0F883
CrashReporter Key:   b10db29977e0d6b2cfa7dac03a40059e16483b4e
Hardware Model:      iPad4,4
OS Version:          iPhone OS 7.1.2 (11D257)
Kernel Version:      Darwin Kernel Version 14.0.0: Thu May 15 23:17:54 PDT 2014; root:xnu-2423.10.71~1/RELEASE_ARM64_S5L8960X
Date:                2014-08-03 17:39:36 -0400
Time since snapshot: 82 ms

Free pages:                              7529
Active pages:                            92838
Inactive pages:                          40921
Speculative pages:                       5992
Throttled pages:                         0
Purgeable pages:                         188
Wired pages:                             84802
File-backed pages:                       10898
Anonymous pages:                         128853
Compressions:                            92719
Decompressions:                          20843
Compressor Size:                         23029
Uncompressed Pages in Compressor:        45391
Largest process:   MobileSafari

Processes
     Name                    <UUID>                       rpages       recent_max   fds      [reason]          (state)

      MobileMail <f359afe7da513629b0a6b8aa32a0b90b>         1310             1310  200   [vm-pageshortage]  (resume) (continuous)
            tccd <e37a9bd3403c34adbbd9d75e9022240a>          193              193  100   [vm-pageshortage]  (daemon)
             kbd <2669fa0ab11a356fbd9482881637e730>         1052             1052  200   [vm-pageshortage]  (daemon)
      librariand <c8d851b111f0324e8de6eaf46ac108d0>          446              446  200   [vm-pageshortage]  (daemon)
    MobileSafari <7d39832f7338323abeb1b07f4b6e80bf>       175625           175625  200   [vm-pageshortage]  (frontmost) (resume)
identityservices <1695cbd72da83c4c87c568bd53a01d24>          469              469  100   [vm-pageshortage]  (daemon)
         imagent <5a1a726d45e033f2bea34c3ae04e817c>          436              436   50   [vm-pageshortage]  (daemon)
           wifid <c0ed3dbc8d7f329489a04faf460c027c>          487              487   50   [vm-pageshortage]  (daemon)
         syslogd <88667a0c3dc6398e9b1c6a0c5a5d8f24>          176              176   50   [vm-pageshortage]  (daemon)
          powerd <1a8551a962783aa9899be0e55a9c1e58>          152              152  100   [vm-pageshortage]  (daemon)
       locationd <3480b01585f039ca9c45ecc16928d8b0>         1120             1120  100   [vm-pageshortage]  (daemon)
   iaptransportd <009cdd0e53bf34829b6a8b69e0ca49bf>          255              255  100   [vm-pageshortage]  (daemon)
    mediaserverd <6c2cee9548813cea95bf5548d3411408>         1142             1142   50   [vm-pageshortage]  (daemon)
   mDNSResponder <090a345fd6e13f52b156a3eb9a0e78ee>          243              243  100   [vm-pageshortage]  (daemon)
            apsd <f96e01aab90637b0822aff105bf78d70>          634              634  100   [vm-pageshortage]  (daemon)
     dataaccessd <ae41b26410e3338ba33e337fb5439069>        14992            14992  200   [vm-pageshortage]  (daemon)
        sharingd <63eae5785eac326987c89d771258ebf8>          565              565   50                      (daemon)
         searchd <240ec06f21843e3d98388dde383d8023>         1784             1784  200                      (daemon)
      calaccessd <438e6dba6616381cbccdc477ba8cc7af>          578              578  200                      (daemon)
          voiced <3918d427306038b1b8196cf1400ea49d>          268              268  200                      (daemon)
            awdd <b525dba7963b337b9723a59a70748516>         1502             1502  200                      (daemon)
assistant_servic <0c34be20da4e3bbbbc372c637991c606>          627              627  200                      (daemon)
      assistantd <5b53d51bff1236baa617758c37d4f862>          978              978  200                      (daemon)
   syncdefaultsd <76f1d98503453b9c90ca39ac5252ac66>          346              346  200                      (daemon)
     SpringBoard <ccb584e84f2f3005a9c20897fdb783dd>         6904             6904   50                     
      backboardd <3085386f5f99357aa9f055e0fb79b827>        23757            23757   50                      (daemon)
       fseventsd <8b8df4c7b46b3dcfb4e1b1d8a6cbb686>          213              213   50                      (daemon)
       lockdownd <6bdd33b3920236808292915812d386c8>          267              267   50                      (daemon)
   wirelessproxd <41e0cf822ff33124b3c3949cedce7fd2>          187              187   50                      (daemon)
         configd <2123dc8c1e103375aec0905809a8d38e>          589              589   50                      (daemon)
            misd <3eb3ea7ff5353113a41f081df88fd2c7>          165              165  100                      (daemon)
    fairplayd.A2 <9948545906083ff9962c310943eb34de>          131              131  100                      (daemon)
      aggregated <178824f7adc231249e9e341c03c36855>          481              481  100                      (daemon)
        BTServer <5540f7e4ecd535b9a48b50258130dbd1>          313              313  100                      (daemon)
       distnoted <a237d6a85cae3c409b914ccb8e5b63f1>          146              146  100                      (daemon)
  UserEventAgent <f9cb9c166628392a9d190acff16950b9>          657              657   50                      (daemon)
        networkd <7262086478d63812ae40c561e8e1acbf>          569              569  100                      (daemon)
filecoordination <4d26113e2e3d3b21832eb866679edf38>          198              198  200                      (daemon)
     touchsetupd <9d37501e59f13ca1b1577435bdb43a9f>          174              174  200                      (daemon)
             ubd <b54681e3319e36b48148ab2026ebf542>          625              625  100                      (daemon)
  CFNetworkAgent <00d26e21f1983f6787c81aa890e4c92e>          197              197  200                      (daemon)
CommCenterClassi <2c4bf0ca27d238fc8f5a25307fcc15ea>          454              454   50                      (daemon)
         notifyd <1d555aa3d08c336294a38d9c134dca00>          233              233  100                      (daemon)

**End**
```

Can anyone else reproduce this?

**Comment by wgbartley** [comment]
It crashes on my 4S and iPad 3.

**Comment by zsup** [comment]
I've been scratching my head on this one - I've seen the problem before but I really have no idea what's causing it or how to fix it. Any theories? Maybe just too much awesome for one page?

**Comment by kennethlimcp** [comment]
@zsup, i just tested this by building locally and it worked fine. All i did was to change https://github.com/spark/docs/blob/master/Gruntfile.coffee#L92 to my laptop's IP address and access via my Android device.

I wonder what's causing the hosted docs to crash.

Placed it behind my home network and exposed it to a url and accessed it without crashing as well.

**Comment by kennethlimcp** [comment]
**UPDATE**

Seems like it's working for docs.spark.io/firmware now...

@eddiezane  and @wgbartley  can you guys confirm this? I hope it was https://github.com/spark/docs/commit/c7e254f162128053f6d864ab3837fbce87a4bc95 that fixed it. ;)

**Comment by eddiezane** [comment]
Confirmed to still be crashing on my iPhone 6 on iOS 8.0 with Safari and Chrome.

**Comment by kennethlimcp** [comment]
@eddiezane, thanks for testing!

Can you try: http://kennethlimcp.no-ip.org:9000

I hosted the docs on my Mac and spin it up locally, exposed via port 9000

**Comment by eddiezane** [comment]
Same results :cry:

**Comment by kennethlimcp** [comment]
Thanks for testing @eddiezane! Appreciate that. One suspicion is that there's too much awesome content inside this particular page.

I have removed half of them. Could you just try again? :dancer:

**Comment by eddiezane** [comment]
@kennethlimcp server appears to be done now.

**Comment by kennethlimcp** [comment]
@joegoggins, can we spin up a staging for docs? I'm having difficulty spinning this up on my server due to dependencies issue.

The aim is to test whether the firmware.md with only half the content would resolve this issue. If that's proven to be true, we can work on splitting the files to smaller sizes!

We can figure this offline and post the link here for @eddiezane and the rest following this PR to test out!

Good for us to figure out what's breaking this before adding new docs to the repo. ;)

**Comment by zsup** [comment]
When we host docs, we simply host the static files that are generated by `grunt build`, so there shouldn't be any need for a server at all for accurate testing. If you're on your local machine and type `grunt build` and then just open in your web browser `index.html` in the build directory, you should have a good staging environment, because all we're doing is hosting those files on Amazon S3

—
Zach Supalla
312.953.3413

**Comment by kennethlimcp** [comment]
I did that and tested with my android phone but the resolved the issue.

However, the same issue persisted on iOS.

So there might be other issues and having more people to test out the staging with the firmware.md stripped down might give us an idea if too much content breaks things

**Comment by joegoggins** [comment]
Hey Kenneth, thanks for helping troubleshooting this!

Though the volume of content on that page could be what's causing iOS to crash, I'd guess there is some particular JavaScript call within the section you removed that is actually the real culprit, or there is a memory leak in all of the pages, but when coupled with this much content causes the crash.  If you (or anyone else reading this issue, :smile: ) wants to dig deeper to find who the real bad guy is and get closer to a fix, I'd recommend using Google Chrome Developer tools to search for memory leaks or step-through debugger to find the JS line that actually causes the crash.

**Comment by kennethlimcp** [comment]
@joegoggins, the weird thing is that i could not reproduce this same issue on my Mac when hosting it locally. That means the issue is not consistent somehow. I'll dig deeper for memory leaks for now. ;)

**Comment by kennethlimcp** [comment]
I wished i had more knowledge about memory leaks but that's all i have found through USB debugging on Android.

![screen shot 2014-10-21 at 22 50 13](https://cloud.githubusercontent.com/assets/6760914/4720753/588d251e-5933-11e4-9cbd-00cef968062b.png)

![screen shot 2014-10-21 at 23 00 10](https://cloud.githubusercontent.com/assets/6760914/4720755/58c95e3a-5933-11e4-94b1-837cf7d7ed52.png)

There seems to be some uncaught exception and increase in the JS heap as the page loads

**Comment by kennethlimcp** [comment]
@eddiezane, i'm going to close this and reopen if something faces the same issue. Thanks!
