### ISSUE TITLE
Recommend the Spark CLI over Putty and CoolTerm for USB connecting + flashing

### ISSUE THREAD

**Issue by joegoggins** [particle-iot-archived/docs-old#208]
The initial "connect" docs were written before the CLI existed, they should be updated to recommend CLI usage over Putty or CoolTerm, this documentation would end up on this page: http://docs.spark.io/connect/

**Comment by kennethlimcp** [comment]
@joegoggins, installing `Spark-cli` might be a little painful for windows user for a start but its an awesome tool that everyone should use!

Thoughts? I can probably write up something to update this page as more hardware gets released and using `Spark-cli` allows a more streamline experience when managing cores of various version ;)

**Comment by joegoggins** [comment]
Yea, good point Kenneth.  Maybe our docs could use a Windows specific section or a "Windows tips" section that takes this into consideration.

**Comment by kennethlimcp** [comment]
This was addressed in https://github.com/spark/docs/commit/b7a04ce6867b4e60be157b4c0526becbae3d23fd so i'm going to close this.
