### ISSUE TITLE
Documentation (and compiler?) Bug: Delay vs delay

### ISSUE THREAD

**Issue by BestLeader** [particle-iot-archived/docs-old#221]
On http://docs.spark.io/firmware/

In the first example, there is the line 
Delay(200);
whereas it should be
delay(200);

Using Delay() instead of delay() does not appear to raise any errors in compiler, but once the code is pushed onto the core, the core becomes unresponsive and requires a complete factory reset to become responsive.

**Comment by bkobkobko** [comment]
There is a core firmware issue to remove access to the wrong delay (Delay()) here:

https://github.com/spark/core-firmware/issues/291

**Comment by kennethlimcp** [comment]
@BestLeader, thanks! i have done a PR for this issue.
