### ISSUE TITLE
Send S3 files to app running on EC2

### ISSUE THREAD

**Issue by asherraz** [particle-iot-archived/docs-old#245]
Hi, fantastic documentation site! Thank you so much for doing this. 

I've got my repo connected to Travis and Travis updating S3. 

However, how do I get the S3 updates over to the application I have running on my EC2 instance? 

Thanks,
Greg

**Comment by zsup** [comment]
Are you trying to contribute to Spark's docs, or build your own? Not sure what the EC2 instance is for, the docs here are deployed entirely as a static site on S3

**Comment by asherraz** [comment]
Hey Zach, yeah, I emailed you about doing it for OpenBCI! Maybe S3 is the way to go instead of using EC2 as well. Thanks man.

**Comment by zsup** [comment]
oh right, didn't put two and two together. Yeah the way we're deploying this is:

1) Set up an S3 bucket that has public permissions (i.e. anything uploaded to it can be downloaded by anyone)
2) Set up Travis to deploy the built site to that S3 bucket
3) Set up DNS to point the preferred domain at that S3 bucket

Hope that helps!
Z

**Comment by asherraz** [comment]
Cool man, thanks a lot. If you have time to answer, I have a few more issues I've run into. 

I included our Amazon Key information in the .travis.yml file on Github and Amazon contacted me saying that I should take that down because I'm at risk. Did you guys deal with that same issue? I notice how you encrypted your secret_access_key, but they said I'm still at risk by having the access_key_id exposed. 

Also, I included the following Bucket Policy on our S3 bucket, and yet it doesn't seem to make the bucket public:

```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "AllowPublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::docs.openbci.com/*"
        }
    ]
}
```

**Comment by zsup** [comment]
re: access key, I don't see why exposing the public one is a security risk, but you should definitely obscure the secret one using Travis's encryption tools. I suppose there's no reason you couldn't use the same tool to expose the public key.

The Bucket Policy looks just like ours, not sure what's wrong there.

**Comment by asherraz** [comment]
Cool, thanks dude. Really appreciate the response.

**Comment by zsup** [comment]
sure thing!
