### ISSUE TITLE
Documentation Needs from the Spark Community

### ISSUE THREAD

**Issue by technobly** [particle-iot-archived/docs-old#249]
https://community.spark.io/t/documentation-needs/4555

An ongoing list of things that need to be documented, as voiced by the Spark Community.

**Comment by AlanGitMan** [comment]
I wonder if I am the only one who remains mystified by the "Local Server" example? 

What I _really_ want from sparkcore is a low cost WAN-connected micro-controller board - so understanding this example - how do I find out what IP address my core has been allocated - is kinda key to that! 

But I am really struggling. I think the cause of my confusion is that I don't really understand how the eco-system it is using is laid out. It's connecting to the core, but its connecting to a server - what server? there is no slot for me to add a server name or IP?- am I supposed to have a server set-up listening on port 9000 already? What's a quick and dirty way to do that? and the "Connect" event/function - how do I initiate that - and to what? 

Could be there is a wonderfully lucid and illustrated article to go with this example, but I haven't found it. Can anyone lighten my darkness for me....?

In any case, IMO, that example on the intro page could do with a lot more comments in the code and an accompanying diagram illustrating the overall scheme of things AND some example commands (as in the other code examples) showing how to use curl or other easily available utilities to make it the entry-level learning tool that it aims to be. 

Thanks as ever
Alan T

**Comment by zsup** [comment]
Hey @AlanGitMan - this is probably a conversation better suited for the community than Github Issues, but in general I agree that we should have more and better documentaiton. In the beginning of next year we'll be putting a lot of effort towards generating better content and tutorials. In the meantime as you work through how the system works if you're up for making any contributions to the docs, we'd appreciate a pull request. Thanks for the feedback!
