### ISSUE TITLE
Documentation for disabling preprocessor

### ISSUE THREAD

**Issue by m-mcgowan** [particle-iot-archived/docs-old#259]
The preprocessor sometimes needs to be disabled with

``` cpp
#pragma SPARK_NO_PREPROCESSOR
```

at the top of the file in order for valid code to compile successfully, but there's currently no published docs for this.

**Comment by technobly** [comment]
FYI, this is only necessary for .INO files compiled with Spark IDE, Spark CLI or Spark Dev (When using Spark CLI).  .CPP files automatically don't get preprocessed.

**Comment by kennethlimcp** [comment]
Moved here: https://github.com/spark/docs/issues/51
