### ISSUE TITLE
Update/remove recently resolved issues.

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot-archived/docs-old#267]
This is totally out of date as well: http://docs.spark.io/troubleshooting/#recently-resolved-issues

Is there a better place to do this than docs?

**Comment by stephpalm** [comment]
I think that's a great point @kennethlimcp. I'm wondering if we should move all of the troubleshooting content over to the support site and just include a link to that in our documentation. What do you think?

cc: @zsup

**Comment by zsup** [comment]
Yeah that feels right

—
Zach Supalla
312.953.3413

**Comment by zsup** [comment]
Although I will say that traffic reports suggest that people haven't really found our support site, so if we move things there we may see more community questions when people don't know the support site exists

—
Zach Supalla
312.953.3413

**Comment by stephpalm** [comment]
Or is the solution to make our support site more visible? Could we put a more obvious link to it on the community site? And maybe work towards integrated search?
