### ISSUE TITLE
Change Spark.sleep() to System.sleep()?

### ISSUE THREAD

**Issue by m-mcgowan** [particle-iot-archived/docs-old#269]
The `Spark` namespace includes variables, functions, pub/sub, connection management and sleep.
The `System` namespace has `reset`, `factoryReset`, `bootloader`. 

The `sleep()` functions are currently in `Spark`, but seems to make more sense to have them in `System`.

They can be moved to `System` in a backwards compatible way (so old code using `Spark` will continue to compile) and we can optionally add a deprecation warning.

**Comment by zsup** [comment]
fully agreed.

**Comment by kennethlimcp** [comment]
Closing this since it is changed in the new firmware and will be documented upon release.
