### ISSUE TITLE
TX/RX swapped in illustration

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot-archived/docs-old#274]
In this diagram, http://docs.spark.io/assets/images/spark-pinout.png, the **TX** and **RX** pin has been incorrectly labeled compared to the actual core.

This is currently displayed here: http://docs.spark.io/hardware/#spark-core-datasheet-pins-and-i-o

since @technobly signed off here, i'm presuming you have the soft copy and changing it would take a few minutes of work ;)

**Comment by kennethlimcp** [comment]
Fixed in: https://github.com/spark/docs/commit/65e0e878f6392e067be198ed4b6bac3b3faffe5f

**Comment by technobly** [comment]
Hey stalker! :)  Thank you for reporting and closing... was JUST going to do that.
