### ISSUE TITLE
Mobile Safari is exploding when viewing the docs page

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot-archived/docs-old#286]
https://community.spark.io/t/internet-explorer/5426/19
We thought this issue was fixed (see #200 ), but it appears this error is back for the remix.

**Comment by pkourany** [comment]
@dmiddlecamp, it is not just Safari but also Chrome.  On Android 4.4, Chrome does not crash but on IOS 8, it does.

**Comment by dmiddlecamp** [comment]
I think mobile Chrome on iOS is really just the same Safari Webkit rendering engine, no?

https://developer.chrome.com/multidevice/ios/overview
