### ISSUE TITLE
More information for spark webhook create

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot-archived/docs-old#301]
Currently, the docs for `spark webhook create` seems to be using an existing `.json` file or at least that's how i am interpreting it reading the information.

Probably need to mention how to setup the `.json` file or have a template lying around for downloading / having a template copy in **Spark-cli** installation

**Comment by technobly** [comment]
Agreed that a template should be added that shows all of the options at once.  A good place to put it would be as an example at the beginning of this section http://docs.spark.io/webhooks/#webhook-options which describes all of those options already.
