### ISSUE TITLE
downsize all images to be mobile friendly

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot-archived/docs-old#302]
There are many high-resolution images (which are fantastic) but might not be mobile friendly in terms of page loading.

Might want to have a lower resolution / size image for the "mobile version" or simply lower the resolution in general to suit web/mobile land

**Comment by technobly** [comment]
I think what could be a good way to do it is a decent sized image that's compressed as JPG, that serves as the "thumbnail" but not necessarily tiny like a thumbnail.  And that links to their larger high res images, possibly PNGs.  And then we document like this:

`[![img-desc](low-res-url)](high-res-url)`

**Comment by kennethlimcp** [comment]
@technobly, that would definitely be rad.

The last time i heard, there's going to be a docs overhaul but haven't been told who is officially in charge. Wouldn't want to spend time doing double work here ;)
