### ISSUE TITLE
document publish rate limits in firmware spark.publish documentation?

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot-archived/docs-old#304]
I didn't see this, is this documented somewhere?

**Comment by kennethlimcp** [comment]
@dmiddlecamp, it is not mentioned somewhere but i thought there's some discussion on the limits being lifted?

**Comment by dmiddlecamp** [comment]
I'm always pushing to raise the limits when it makes sense, but in the meantime we should at least document what's in place now so people aren't caught offguard.  We've been talking about better feedback mechanisms for when things are rate limited, so it's more clear what's happening.

**Comment by kennethlimcp** [comment]
@dmiddlecamp,

just to clarify before i send in a PR.

1.) No more than 1 `Spark.publish()` per second 

2.) Bursts of up to 4 per second?

**Comment by dmiddlecamp** [comment]
Heya @kennethlimcp,

  That's about right, a rate of about 1 a second, with bursts of up to 4 allowed from the firmware.

Thanks!
David

**Comment by kennethlimcp** [comment]
Here's the PR!

**Comment by technobly** [comment]
Thought I'd mention if you burst 4 messages back to back, it takes 4 seconds to recover before you can send 1 per second again.
