### ISSUE TITLE
Wrong value in Time.zone() example

### ISSUE THREAD

**Issue by pcamp** [particle-iot-archived/docs-old#310]
The comment says "Set time zone to Eastern USA daylight saving time", so it should be `Time.zone(-4);` rather than `Time.zone(-5);`.

Reference: http://www.timeanddate.com/time/zones/edt

**Comment by kennethlimcp** [comment]
@pcamp i don't live in US so i'm not sure about this but the idea is that you can actually adjust the time zone offset (+/-) from UTC.

Does the Eastern daylight time saving time change or fixed to -4? I'm just guessing it depends on which parts of the year? :smile_cat:

**Comment by pcamp** [comment]
Eastern Daylight Time is always -4, but it is only used for part of the year.  During the rest of the year, the Eastern USA uses Eastern Standard Time, which is always -5.

**Comment by kennethlimcp** [comment]
Sounds good! I shall change this. @technobly, can you just confirm this daylight time change is correct?

**Comment by towynlin** [comment]
Thanks for pointing out this error @pcamp —yes @kennethlimcp :+1: this comment correctly says that EDT is always UTC-4 (only in use during the summer months), while the same part of the U.S. uses EST (UTC-5) for the winter months. And thanks Kenneth for getting clarification; time zones can definitely be confusing. :smile:

**Comment by kennethlimcp** [comment]
@pcamp and @towynlin, thanks! Here's the fix as promised.
