### ISSUE TITLE
DFU Mode (Device Firmware Upgrade) - should link to dfu-util / how to install dfu-util ?

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot-archived/docs-old#328]
orig section:
http://docs.particle.io/core/modes/#core-modes-dfu-mode-device-firmware-upgrade

Maybe?   http://dfu-util.sourceforge.net/

**Comment by kennethlimcp** [comment]
Moved here: https://github.com/spark/docs/issues/53
