### ISSUE TITLE
spark.io/start suggestion

### ISSUE THREAD

**Issue by chani3** [particle-iot-archived/docs-old#74]
I am very jetlagged, and just barely managing to follow instructions. so I raninto the problem that neither your site nor your app tells me when I'm supposed to plug in the actual chip to power :)

... apparently power wasn't enough. I can't get past "let's connect your core"

**Comment by chani3** [comment]
power _and_ antenna, I needed to be reminded of those both.

**Comment by joegoggins** [comment]
closing this issue, addressed via @wgbartley 's pull request. Thanks for bringing this up @chani3
