### ISSUE TITLE
Document that mobile apps will claim all devices in listening mode

### ISSUE THREAD

**Issue by chani3** [particle-iot-archived/docs-old#75]
Initial issue from @chani3 "whoops, I claimed someone else's device. :) the spark guys fixed it but maybe that should be documented. or fixed. or something."

Spec to fix this:

Add a sentence or paragraph to this page: http://docs.spark.io/#/connect/connecting-your-core-smart-config-with-the-spark-app mentioning that smart config will claim any core listening on the same network.  Should hint that it's not the ideal method to configure in a workshop or conference setting.

**Comment by joegoggins** [comment]
Thanks for the feedback @chani3 and sorry for the delay acknowledging! 
I've refined the description of the issue into something actionable so we can tackle this at some point soon.

**Comment by kennethlimcp** [comment]
fixed with #188
