### ISSUE TITLE
Broken link to bootloader repository

### ISSUE THREAD

**Issue by amanfredi** [particle-iot-archived/docs-old#81]
In start.md line 272, there's a link to github.com/spark/bootloader, but that repository doesn't exist (or is not public).

**Comment by towynlin** [comment]
Thanks @amanfredi, the README for the bootloader is REALLY out of date and doesn't describe the current state of things at all.  We'll open source the bootloader as soon as we can revise the README.  I'll make a note to this effect in the docs today.  Thanks!

**Comment by wgbartley** [comment]
It looks like there is no longer a link to any bootloader repository in `start.md` any more.  Should this issue be closed?

**Comment by joegoggins** [comment]
Yep. I removed that link the other day. Closing. Thanks for bringing this up.
