### ISSUE TITLE
Android app won't allow password-less WiFi networks

### ISSUE THREAD

**Issue by swsnider** [particle-iot-archived/docs-old#87]
When I try to use the app to set up my new spark core, it gives me the screen below:
![screenshot_2013-12-18-18-42-58](https://f.cloud.github.com/assets/1662/1779781/6fdc16da-6857-11e3-9d90-9510f345fcfd.png)

See how the button is dimmed? It doesn't respond to taps either :(.

**Comment by zsup** [comment]
We just published an update that fixes this; it should hit your phone
within 24 hours.

**Comment by joegoggins** [comment]
Marking this resolved. Let us know if the issue persists.
