### ISSUE TITLE
Tinker giving error message "404", no longer able to Tinker 

### ISSUE THREAD

**Issue by ThomSirveaux** [particle-iot-archived/docs-old#97]
Just as the title says. Using Android on a Moto X, worked for about 30 minutes hooked up to a 4 channel relay I've got, then when I tried to toggle D7, I received the following message, and can no longer use the app. 
![screenshot_2014-01-27-21-49-42](https://f.cloud.github.com/assets/6521688/2016583/5f0829a4-87e0-11e3-8ddf-ea10a0b35156.png)

**Comment by zsup** [comment]
Hi @ThomSirveaux - did you try resetting the Core? Also, did you flash new code to the Core? If so, it won't recognize Tinker commands anymore.

**Comment by ThomSirveaux** [comment]
Never flashed new code, but I'm attempting to refresh Tinker, now.

**Comment by ThomSirveaux** [comment]
Aaaaand I'm an idiot. Reflashed Tinker and it works.

**Comment by zsup** [comment]
Cool, glad you're back in action!
